"""empty message

Revision ID: 3f86f5cab0cb
Revises: 94b7d4cd8c0a
Create Date: 2023-06-09 22:58:31.802990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f86f5cab0cb'
down_revision = '94b7d4cd8c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poridhian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Text(), nullable=True))
        batch_op.drop_column('occupation')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poridhian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###
